# Generated by Django 3.2.5 on 2022-06-08 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('building', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Building_name')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('question_text1', models.IntegerField(verbose_name='Do you prefer popular places with a lot of foot traffic over quiet places?')),
                ('question_text2', models.IntegerField(verbose_name='Do you like to explore popular places?')),
                ('question_text3', models.IntegerField(verbose_name='Are you willing to spend money on pricey experiences?')),
                ('question_text4', models.IntegerField(verbose_name='Do you like to explore nature and green spaces when in a new city?')),
                ('question_text5', models.IntegerField(verbose_name='Is it important to you to go to scenic places with great photo opportunities?')),
                ('question_text6', models.IntegerField(verbose_name='Do you travel with your pet(s) or like to go to animal-friendly places (i.e. dog parks)?')),
                ('question_text7', models.IntegerField(verbose_name='Are you into literature and books?')),
                ('question_text8', models.IntegerField(verbose_name='Do you like laid-back and casual spots?')),
                ('question_text9', models.IntegerField(verbose_name='Do you need publicly available Wifi options during your visit?')),
                ('question_text10', models.IntegerField(verbose_name='Are you interested in history and historic places?')),
                ('question_text11', models.IntegerField(verbose_name='Are you a person that likes to visit museums (art, history, curiosities, etc.)?')),
                ('question_text12', models.IntegerField(verbose_name='Do you enjoy street performances?')),
                ('question_text13', models.IntegerField(verbose_name='Are you looking for authentic local experiences?')),
                ('question_text14', models.IntegerField(verbose_name='Are you a sporty person and looking for sports opportunities while travelling?')),
                ('question_text15', models.IntegerField(verbose_name='Do you usually travel with your family and look for family-friendly places?')),
                ('question_text16', models.IntegerField(verbose_name='Are you travelling with a romantic partner and want to find a special place to take them to?')),
                ('description', models.CharField(max_length=1000, verbose_name='Building Description')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('surname', models.CharField(max_length=200, verbose_name='Surame')),
                ('question_text1', models.IntegerField(verbose_name='Do you prefer popular places with a lot of foot traffic over quiet places?')),
                ('question_text2', models.IntegerField(verbose_name='Do you like to explore popular places?')),
                ('question_text3', models.IntegerField(verbose_name='Are you willing to spend money on pricey experiences?')),
                ('question_text4', models.IntegerField(verbose_name='Do you like to explore nature and green spaces when in a new city?')),
                ('question_text5', models.IntegerField(verbose_name='Is it important to you to go to scenic places with great photo opportunities?')),
                ('question_text6', models.IntegerField(verbose_name='Do you travel with your pet(s) or like to go to animal-friendly places (i.e. dog parks)?')),
                ('question_text7', models.IntegerField(verbose_name='Are you into literature and books?')),
                ('question_text8', models.IntegerField(verbose_name='Do you like laid-back and casual spots?')),
                ('question_text9', models.IntegerField(verbose_name='Do you need publicly available Wifi options during your visit?')),
                ('question_text10', models.IntegerField(verbose_name='Are you interested in history and historic places?')),
                ('question_text11', models.IntegerField(verbose_name='Are you a person that likes to visit museums (art, history, curiosities, etc.)?')),
                ('question_text12', models.IntegerField(verbose_name='Do you enjoy street performances?')),
                ('question_text13', models.IntegerField(verbose_name='Are you looking for authentic local experiences?')),
                ('question_text14', models.IntegerField(verbose_name='Are you a sporty person and looking for sports opportunities while travelling?')),
                ('question_text15', models.IntegerField(verbose_name='Do you usually travel with your family and look for family-friendly places?')),
                ('question_text16', models.IntegerField(verbose_name='Are you travelling with a romantic partner and want to find a special place to take them to?')),
                ('dot_product', models.FloatField(default=0, verbose_name='Validation_Dot_Product')),
                ('valuation', models.FloatField(default=0, verbose_name='Validation')),
                ('opinion', models.CharField(default='No Opinion', max_length=1000, verbose_name='Opinion')),
                ('building', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
